### ISSUE TITLE
create database from framework

### ISSUE THREAD

**Issue by maherkhalil07** [nemesiscodex/actix-todo#3]
Can we connect and create the database from framework not using terminal?

**Comment by nemesiscodex** [comment]
yes, it can be done with http://diesel.rs. You can create and run migrations using the cli  http://diesel.rs/guides/configuring-diesel-cli/

**Comment by maherkhalil07** [comment]
Appreciate your help
Thanks

**Comment by nemesiscodex** [comment]
@maherkhalil07 I added diesel to the repo and updated the readme, so I will close this. (A video about that will come soon)
